name: Release
on:
  push:
    tags:
      - "*"

env:
  linux_image: "node:20-bullseye-slim"

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [linux/amd64]

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build ${{ matrix.arch }}
        run: |
          docker run --platform ${{ matrix.arch }} --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace ${{ env.linux_image }} /bin/sh -c '
            apt update
            apt install -y build-essential libsdl2-dev wget
            make
            mv main whisper
            models/download-ggml-model.sh tiny
            models/download-ggml-model.sh base
            ./quantize models/ggml-base.bin ggml-base-q5_0.bin q5_0
            '

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "whisper, models/ggml-tiny.bin, ggml-base-q5_0.bin"
          allowUpdates: true
          replacesArtifacts: false

  macos-14:
    runs-on: macos-14

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Dependencies
        run: |
          brew update
          brew install sdl2

      - name: Build
        run: |
          make
          make stream
          mv main whisper_macos_m1

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "whisper_macos_m1"
          allowUpdates: true
          replacesArtifacts: false
